### ISSUE TITLE
Update site

### ISSUE THREAD

**Issue by joeljk13** [RocHack/rocbuses#10]
https://rochack.org/rocbuses/ still doesn't include the purple line, even though it's been updated on the master branch here.

**Comment by clehner** [comment]
The appcache is probably not updating. Try viewing the site in private browsing. Also try pushing a change to the appcache manifest file (e.g. increment the top comment) and then checking again.

**Comment by niebloomj** [comment]
Mine shows purple line

**Comment by joeljk13** [comment]
Yeah, Firefox was having caching issues. It worked once I ctrl-refreshed the index.html, script.js, and style.css files.
